import useRevenueCat from "@/hooks/RevenueCat";

export const roles = [
  {
    name: "Villager",
    image: require("../assets/images/characters/villager.jpeg"),
    min: 3,
    max: 25,
    amount: 2,
    unlocked: true,
    need_pro_membership: false,
  },
  {
    name: "Werewolf",
    image: require("../assets/images/characters/werewolf.jpeg"),
    min: 1,
    max: 4,
    amount: 1,
    unlocked: true,
    need_pro_membership: false,
  },
  {
    name: "Seer",
    image: require("../assets/images/characters/seer.jpeg"),
    min: 0,
    max: 1,
    amount: 0,
    unlocked: true,
    need_pro_membership: false,
  },
  {
    name: "Doctor",
    image: require("../assets/images/characters/doctor.jpg"),
    min: 0,
    max: 1,
    amount: 0,
    unlocked: false,
    need_pro_membership: true,
  },
  {
    name: "Bodyguard",
    image: require("../assets/images/characters/bodyguard.jpeg"),
    min: 0,
    max: 1,
    amount: 0,
    unlocked: false,
    need_pro_membership: true,
  },
  {
    name: "Hunter",
    image: require("../assets/images/characters/hunter.jpg"),
    min: 0,
    max: 1,
    amount: 0,
    unlocked: false,
    need_pro_membership: true,
  },
  {
    name: "Priest",
    image: require("../assets/images/characters/priest.jpg"),
    min: 0,
    max: 1,
    amount: 0,
    unlocked: false,
    need_pro_membership: true,
  },
  {
    name: "Prince",
    image: require("../assets/images/characters/prince.jpeg"),
    min: 0,
    max: 1,
    amount: 0,
    unlocked: false,
    need_pro_membership: true,
  },
  {
    name: "Witch",
    image: require("../assets/images/characters/witch.jpeg"),
    min: 0,
    max: 1,
    amount: 0,
    unlocked: false,
    need_pro_membership: true,
  },
  {
    name: "Tanner",
    image: require("../assets/images/characters/lurker3.jpeg"),
    min: 0,
    max: 1,
    amount: 0,
    unlocked: false,
    need_pro_membership: true,
  },
  {
    name: "Alpha Werewolf",
    image: require("../assets/images/characters/alpha-werewolf.jpg"),
    min: 0,
    max: 1,
    amount: 0,
    unlocked: false,
    need_pro_membership: true,
  },
  {
    name: "Lycan",
    image: require("../assets/images/characters/lycan.jpeg"),
    min: 0,
    max: 2,
    amount: 0,
    unlocked: false,
    need_pro_membership: true,
  },
  {
    name: "Cursed Villager",
    image: require("../assets/images/characters/cursed-villager.jpeg"),
    min: 0,
    max: 2,
    amount: 0,
    unlocked: false,
    need_pro_membership: true,
  },
  {
    name: "Cupid",
    image: require("../assets/images/characters/cupid.jpeg"),
    min: 0,
    max: 1,
    amount: 0,
    unlocked: false,
    need_pro_membership: true,
  },
  {
    name: "Wolf Cub",
    image: require("../assets/images/characters/wolf-cub.jpeg"),
    min: 0,
    max: 1,
    amount: 0,
    unlocked: false,
    need_pro_membership: true,
  },
];
